### ISSUE TITLE
Resolve the rusty-hermit name clash

### ISSUE THREAD

**Issue by jounathaen** [hermitcore/kernel#35]
### Current Situation:

The naming of the repositories and the crates is contradictory.

| Crate Name | Repository Name| Task |
|----|----|----|
| rusty-hermit | https://github.com/hermitcore/libhermit-rs | The Kernel itself |
| hermit-sys | https://github.com/hermitcore/rusty-hermit  | FFI - What is actually imported in the applications. `libhermit-rs` is downloaded and linked in the magic `build.rs` script|

### Problems

- Public resources like papers etc link to https://github.com/hermitcore/libhermit-rs, so the URL _always_ has to point to the "Cenral" repository.
- crates.io links to https://github.com/hermitcore/rusty-hermit. I don't know if the links there could be changed retrospectively.

### Solution Attempts

These are the two solutions I came up with

#### Rename the Repository Attempt
- Move the content of https://github.com/hermitcore/rusty-hermit to a differently named repository. 
- Update crates.io to the new location
- Move this repository to the now free rusty-hermit url. **This implies breakage**

#### Rename this Crate Attempt
- change the name of this crate to libhermit-rs
- update the crate name in hermit-sys/hermit-loader/...

**Comment by jounathaen** [comment]
Another Solution Attempt:
### Merge Everything Attempt
- Put libhermit-rs into the rusty-hermit repository (not as a submodule)
- Leave a link to rusty-hermit at this repository

**Comment by stlankes** [comment]
Do we solve the issue? I think that #77 describes the remaining problem.

**Comment by jounathaen** [comment]
Ah, the remaining problem I almost forgot about is, that the crate names are still mixed up

**Comment by mkroening** [comment]
@jounathaen, do you feel like the "Rename this Crate Attempt" has been successful in https://github.com/hermitcore/libhermit-rs/pull/505 so that this issue can be closed?

**Comment by jounathaen** [comment]
Yes, this is resolved now! :partying_face:
